### ISSUE TITLE
Large parquet file OOM crash

### ISSUE THREAD

**Issue by mvberg** [CrunchyData/pg_parquet#88]
Hi All,

When attempting to copy a rather wide (and large) parquet file, the process appears to grow memory indefinitely, and is ultimately killed with sig 9. 

Running pg17 (plain config) in docker (gave the VM 16GB memory) on an M2 air.

### OOM Crash

```
2024-12-12 19:35:06.199 UTC [328] LOG:  checkpoint starting: time
2024-12-12 19:35:34.642 UTC [249] LOG:  server process (PID 333) was terminated by signal 9: Killed
2024-12-12 19:35:34.642 UTC [249] DETAIL:  Failed process was running: COPY opt FROM '/tmp/options.parquet';
2024-12-12 19:35:34.642 UTC [249] LOG:  terminating any other active server processes
2024-12-12 19:35:34.644 UTC [249] LOG:  all server processes terminated; reinitializing
```

### File Details

| uri                  | row_group_id | row_group_num_rows | row_group_num_columns | row_group_bytes | column_id | file_offset | num_values | path_in_schema | type_name  | stats_null_count | stats_distinct_count | stats_min             | stats_max         | compression | encodings | index_page_offset | dictionary_page_offset | data_page_offset | total_compressed_size | total_uncompressed_size |
|----------------------|--------------|--------------------|-----------------------|-----------------|-----------|-------------|------------|----------------|------------|------------------|----------------------|-----------------------|-------------------|-------------|-----------|-------------------|------------------------|------------------|-----------------------|-------------------------|
| /tmp/options.parquet |            0 |             123061 |                    78 |        84656300 |         0 |           0 |     123061 | column00       | BYTE_ARRAY |                0 |                      | $DJX\|20241213\|325.00C | A\|20270115\|95.00P | SNAPPY      | PLAIN     |                   |                        |                4 |                614320 |                 2977184 |

It's about 420MB on disk (convered to parquet from csv using duckdb py bindings - default options) - the same file will load in CSV format using the `copy` command. CSV file is about 1.3GB and completes on my M2 Air in about 12 seconds (1.5M rows).

Schema [here](https://gist.github.com/mvberg/14c73a40f29e392729511c7d1c36186c)

Any suggestions or insights? Is it expected to use that amount of memory (or more) based on the size of the parquet file? Let me know if I can provide more information. Thanks!

**Comment by aykut-bozkurt** [comment]
Hi @mvberg, thanks for reporting. It should not take space that is much higher (some of extra allocations are made by Postgres) than single row group size because we process each row group sequentially when reading the file.

You can **mitigate** it if you are able to control the creation of the file. You can try reducing `row_group_size`. (this is done like `COPY table TO '/tmp/test.parquet' with (row_group_size 10000)` with pg_parquet. Probably you can set it from whatever tool you use) That will let the parquet reader process less rows per each row group and probably mitigate the problem. (you can play with the row group size)

When I create the similar size file, I could see "COPY FROM" can consume space ~ 10GB per each row group (for default row group size ~120_000). This is due to some unexpected allocations by Postgres. (that should be regularly freed by us)
I would open **a PR to fix** it. But till then, mitigation could be as above.
